### ISSUE TITLE
COUNT (DISTINCT Y) generate an error

### ISSUE THREAD

**Issue by Starmind-Nicolas-Blexmann** [klahnakoski/moz-sql-parser#2]
I tried to parse the following line:
parse("SELECT COUNT(DISTINCT Y) FROM A ")
Got this error:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Github\sol-etl-process-service\venv\lib\site-packages\moz_sql_parser\__init__.py", line 31, in parse
    parse_result = SQLParser.parseString(sql, parseAll=True)
  File "D:\Github\sol-etl-process-service\venv\lib\site-packages\mo_parsing\core.py", line 73, in output
    return func(*args, **kwargs)
  File "D:\Github\sol-etl-process-service\venv\lib\site-packages\mo_parsing\core.py", line 319, in parseString
    raise exc
  File "D:\Github\sol-etl-process-service\venv\lib\site-packages\mo_parsing\core.py", line 317, in parseString
    se._parse(string, loc)
  File "D:\Github\sol-etl-process-service\venv\lib\site-packages\mo_parsing\core.py", line 222, in _parse
    loc, tokens = self.parseImpl(string, preloc, doActions)
  File "D:\Github\sol-etl-process-service\venv\lib\site-packages\mo_parsing\expressions.py", line 198, in parseImpl
    raise pe
  File "D:\Github\sol-etl-process-service\venv\lib\site-packages\mo_parsing\expressions.py", line 190, in parseImpl
    loc, exprtokens = expr._parse(string, loc, doActions)
  File "D:\Github\sol-etl-process-service\venv\lib\site-packages\mo_parsing\core.py", line 222, in _parse
    loc, tokens = self.parseImpl(string, preloc, doActions)
  File "D:\Github\sol-etl-process-service\venv\lib\site-packages\mo_parsing\tokens.py", line 1120, in parseImpl
    raise ParseException(self, loc, string)
mo_parsing.exceptions.ParseException: Expecting StringEnd, found '('  (at char 12), (line:1, col:13)

Thanks

**Comment by klahnakoski** [comment]
fixed in version  3.146.20326   

I hope this suitable:

https://github.com/klahnakoski/moz-sql-parser/commit/c625fb6b52250fac4af55491d54e30fd8553d2d6#diff-61d5a1a018e97cc478eba974e6abfff036bf58e449578b7b680fab7f2e63976dR1098

I am assuming `DISTINCT` variations are all special cases; I have no doubt there are other variations that are not parsed properly

**Comment by klahnakoski** [comment]
Alternatively, we may consider rewriting the whole statement into older SQL:

```
 {"from": "A", "select": {"value":{"count": 1}}, "group_by": "Y"}
```

The benefit would be we can check, and fail, if there is a `group by` clause

**Comment by Starmind-Nicolas-Blexmann** [comment]
@klahnakoski Thanks, unfortunately, it doesn't work if there is more than one output:
"SELECT COUNT( DISTINCT B), A FROM C WHERE D= X GROUP BY A" will fail

**Comment by klahnakoski** [comment]
Thank you. I am going to need a full specification so I stop guessing.  Looking....

**Comment by klahnakoski** [comment]
... I went with more guessing

**Comment by klahnakoski** [comment]
Here is one non-trivial  DISTINCT example:

https://www.ibm.com/support/knowledgecenter/SSGU8G_12.1.0/com.ibm.sqls.doc/ids_sqs_1581.htm

**Comment by Starmind-Nicolas-Blexmann** [comment]
@klahnakoski Can you use this example as spec? I don't really see what to add to this.
I can only suggest this: Transform COUNT(DISTINCT A) in {value: {count:{distinct:"A"}}}
This is just a suggestion. My point is mostly to avoid Exception when calling such a function

**Comment by klahnakoski** [comment]
`DISTINCT` is treated as a function; consuming all available parameters that follow it.  Unfortunately, this means `DISTINCT` can be used more than once in a select clause.  eg `SELECT DISTINCT a, b DISTINCT c`.  I will let the higher level system deal with that.

In any case, `COUNT(DISTINCT A))` is now parsed to `{"value": {"count": {"distinct": "A"}}}`

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/6191ba9aec1f423ddf90d269a72312f3c6fa130c
